### PR TITLE
add ability to preserve words from being cut

### PR DESCRIPTION
**Pull request by quentinus95**
I have added the ability to preserve words from being cut.

### CODE REVIEW

**Comment by quentinus95** [comment]
It is too complicated to take in account the ellipses size, the original string size, the limit size and avoiding words to be cutted (and I think it is a bit confusing) so I changed the filter to truncate the sentence to `length` size and add the ellipses.

Do you agree with these changes?

**Comment by quentinus95** [comment]
ping @wy-ei

**Comment by wy-ei** [comment]
@quentinus95 If cut the origin string to specific length, things are getting clear. but this change may be impact other people who use this filter. I will change this filter in next minor version. thanks for your idea.

**Comment by quentinus95** [comment]
@wy-ei do you have an idea on when you will change the filter?

Thx

**Comment by wy-ei** [comment]
Tomorrow, I will do it at tomorrow, sorry I am a totally procrastinator. 😭

**Pull request merged**
